-- Hirono: word_groups のみ（8カラム構成）
-- Run in Supabase: SQL Editor → New query → Paste → Run
-- 既存テーブルがある場合: drop table if exists words; drop table if exists word_groups; を先に実行
--
-- 全レコード共通フォーマット（今日の単語でランダムに1件表示）:
--   root_word      → 今日のcode（例: const, cur/curs, put）
--   root_meaning   → meaning（例: 共に＋立つ）
--   derivatives    → 覚えよう [{"word":"...","meaning":"..."}]
--   examples       → 例文 [{"text":"... ____ ...","answer":"..."}]  空欄は ____
--   example_sentence_en/jpn → 参考例文（任意）
--   relevent       → ○×クイズ用（true=仲間, false=仲間ではない）

create table if not exists word_groups (
  id bigint primary key generated by default as identity,
  root_word text not null,
  root_meaning text not null,
  derivatives jsonb default '[]',
  examples jsonb default '[]',
  example_sentence_en text,
  example_sentence_jpn text,
  relevent boolean not null default true
);

comment on column word_groups.root_word is '語根または単語';
comment on column word_groups.root_meaning is '意味';
comment on column word_groups.derivatives is '派生語リスト。例: [{"word":"cursor","meaning":"カーソル"}]';
comment on column word_groups.examples is '穴埋め問題。例: [{"text":"Move the ____ to the end.","answer":"cursor"}]';
comment on column word_groups.example_sentence_en is '参考例文（英語）';
comment on column word_groups.example_sentence_jpn is '参考例文（日本語）';
comment on column word_groups.relevent is '○×クイズ用: この単語は語根の仲間か（true=○, false=×）';

alter table word_groups enable row level security;
create policy "Allow public read word_groups"
  on word_groups for select using (true);

-- サンプル（初回のみ）
insert into word_groups (root_word, root_meaning, derivatives, examples, example_sentence_en, example_sentence_jpn, relevent)
select
  'cur / curs',
  '走る、流れる (run, flow)',
  '[{"word":"cursor","meaning":"カーソル"},{"word":"current","meaning":"現在の、流れ"},{"word":"occur","meaning":"起こる"}]'::jsonb,
  '[{"text":"Move the ____ to the end of the line.","answer":"cursor"},{"text":"The ____ version supports dark mode.","answer":"current"}]'::jsonb,
  'Move the cursor to the end of the line.',
  'カーソルを行末に移動する。',
  true
where not exists (select 1 from word_groups limit 1);

-- ○×用サンプル（仲間ではない例）
insert into word_groups (root_word, root_meaning, derivatives, examples, example_sentence_en, example_sentence_jpn, relevent)
select
  'apple',
  'りんご（語根とは無関係の単語）',
  '[]'::jsonb,
  '[]'::jsonb,
  null,
  null,
  false
where (select count(*) from word_groups) < 2;

-- 語根「put」サンプル（穴埋め・復習用）
insert into word_groups (root_word, root_meaning, derivatives, examples, example_sentence_en, example_sentence_jpn, relevent)
select
  'put',
  '考える (think)',
  '[{"word":"compute","meaning":"計算する"},{"word":"computer","meaning":"コンピュータ"},{"word":"reputation","meaning":"評判"}]'::jsonb,
  '[{"text":"____ the total and return the result.","answer":"Compute"},{"text":"A ____ can process data quickly.","answer":"computer"}]'::jsonb,
  'Compute the sum and display the result.',
  '合計を計算して結果を表示する。',
  true
where not exists (select 1 from word_groups where root_word = 'put' limit 1);

-- 語根「const」サンプル（今日のcode / 覚えよう / 例文・ホバーで答え表示＋読み上げ用）
insert into word_groups (root_word, root_meaning, derivatives, examples, example_sentence_en, example_sentence_jpn, relevent)
select
  'const',
  '共に＋立つ',
  '[{"word":"constant","meaning":"絶え間なく・常に"},{"word":"constitution","meaning":"憲法"},{"word":"construct","meaning":"建設する"},{"word":"distance","meaning":"距離"}]'::jsonb,
  '[{"text":"The speed of the car was ____ .","answer":"constant"},{"text":"What is the ____ between Hirono and Hachimantai?","answer":"distance"}]'::jsonb,
  null,
  null,
  true
where not exists (select 1 from word_groups where root_word = 'const' limit 1);
