-- =============================================================================
-- word_groups + words 統合スキーマ（追加例文・同義語対応）
-- Supabase SQL Editor に貼り付けて Run。既存の word_groups/words がある場合は
-- 先に drop するか、別プロジェクトで実行してください。
-- =============================================================================

-- 1) 語根グループ（穴埋め・○×クイズ用。既存の8カラム）
create table if not exists word_groups (
  id bigint primary key generated by default as identity,
  root_word text not null,
  root_meaning text not null,
  derivatives jsonb default '[]',
  examples jsonb default '[]',
  example_sentence_en text,
  example_sentence_jpn text,
  relevent boolean not null default true
);

-- 2) 単語（語根に紐づく。追加例文・同義語用カラムあり）
create table if not exists words (
  id bigint primary key generated by default as identity,
  group_id bigint not null references word_groups(id) on delete cascade,
  en text not null,
  jp text not null,
  note text,
  sort_order int not null default 0,
  -- 穴埋め用（1単語につき複数問）
  examples jsonb default '[]',
  -- 代表例文（1件）
  example_sentence_en text,
  example_sentence_jpn text,
  -- 同義語: 同じ意味の別単語。 [{"word_id": 2}, {"word_id": 5}] で他単語と紐づけ
  -- または [{"en": "term", "meaning": "意味"}] でテキストのみ
  synonyms jsonb default '[]',
  created_at timestamptz default now()
);

-- 3) 追加例文（1単語に複数例文を登録）
create table if not exists word_examples (
  id bigint primary key generated by default as identity,
  word_id bigint not null references words(id) on delete cascade,
  sentence_en text,
  sentence_jp text,
  sort_order int not null default 0,
  created_at timestamptz default now()
);

comment on column word_groups.derivatives is '派生語。例: [{"word":"cursor","meaning":"カーソル"}]';
comment on column word_groups.examples is '穴埋め。例: [{"text":"Move the ____ to the end.","answer":"cursor"}]';
comment on column words.examples is '穴埋め。例: [{"text":"... ____ ...","answer":"..."}]';
comment on column words.synonyms is '同義語。例: [{"word_id":2}] または [{"en":"term","meaning":"意味"}]';
comment on table word_examples is '単語に紐づく追加例文（複数可）';

-- RLS
alter table word_groups enable row level security;
alter table words enable row level security;
alter table word_examples enable row level security;

create policy "Allow public read word_groups" on word_groups for select using (true);
create policy "Allow public read words" on words for select using (true);
create policy "Allow public read word_examples" on word_examples for select using (true);

-- インデックス（任意）
create index if not exists words_group_id_idx on words(group_id);
create index if not exists word_examples_word_id_idx on word_examples(word_id);

-- =============================================================================
-- サンプルデータ（語根1件 + 単語3件 + 追加例文・同義語）
-- =============================================================================

insert into word_groups (root_word, root_meaning, derivatives, examples, example_sentence_en, example_sentence_jpn, relevent)
select
  'cur / curs',
  '走る、流れる (run, flow)',
  '[{"word":"cursor","meaning":"カーソル"},{"word":"current","meaning":"現在の"},{"word":"occur","meaning":"起こる"}]'::jsonb,
  '[{"text":"Move the ____ to the end of the line.","answer":"cursor"},{"text":"The ____ version supports dark mode.","answer":"current"}]'::jsonb,
  'Move the cursor to the end of the line.',
  'カーソルを行末に移動する。',
  true
where not exists (select 1 from word_groups where root_word = 'cur / curs' limit 1);

-- 上で挿入した語根の id を使って単語を挿入（1件だけサンプル）
insert into words (group_id, en, jp, note, sort_order, examples, example_sentence_en, example_sentence_jpn, synonyms)
select
  g.id,
  'cursor',
  'カーソル（画面上の位置を示す印）',
  '流れていくもの → 現在位置',
  1,
  '[{"text":"Move the ____ to the end of the line.","answer":"cursor"}]'::jsonb,
  'Move the cursor to the end of the line.',
  'カーソルを行末に移動する。',
  '[]'::jsonb
from word_groups g
where g.root_word = 'cur / curs'
  and not exists (select 1 from words w2 where w2.group_id = g.id and w2.en = 'cursor')
limit 1;

-- 2件目の単語（current）。synonyms で cursor との関連をテキストで持つ例
insert into words (group_id, en, jp, note, sort_order, examples, example_sentence_en, example_sentence_jpn, synonyms)
select
  g.id,
  'current',
  '現在の、電流、流れ',
  '今流れているもの',
  2,
  '[{"text":"The ____ version supports dark mode.","answer":"current"}]'::jsonb,
  'The current version supports dark mode.',
  '現在のバージョンはダークモードに対応している。',
  '[{"en":"cursor","meaning":"カーソル（関連語）"}]'::jsonb
from word_groups g
where g.root_word = 'cur / curs'
  and not exists (select 1 from words w2 where w2.group_id = g.id and w2.en = 'current')
limit 1;

-- 追加例文（word_examples）は words の id が決まってから挿入
-- 例: cursor に追加例文を1件
insert into word_examples (word_id, sentence_en, sentence_jp, sort_order)
select w.id, 'Click where you want to place the cursor.', 'カーソルを置きたい位置をクリックする。', 0
from words w
join word_groups g on g.id = w.group_id
where g.root_word = 'cur / curs' and w.en = 'cursor'
limit 1;

-- =============================================================================
-- 使い方メモ
-- =============================================================================
-- 【word_groups】 語根単位の穴埋め・○×・派生語リスト（Hirono 学習ページ用）
-- 【words】      語根に属する単語。examples=穴埋め、example_sentence_*=代表例文、synonyms=同義語
-- 【word_examples】 1単語に複数の追加例文
--
-- 同義語の入れ方:
--   A) 他単語を参照: synonyms = [{"word_id": 2}]  （words.id=2 の単語を同義語として表示）
--   B) テキストのみ: synonyms = [{"en": "pointer", "meaning": "ポインタ（類似）"}]
--
-- 追加例文: word_examples に word_id で紐づけて insert
--   insert into word_examples (word_id, sentence_en, sentence_jp, sort_order)
--   values (1, 'English sentence.', '日本語の文。', 0);
