-- 1) 普通の例文：word_id に紐づくテーブル（語彙カードで表示）
-- 2) 穴埋め：words の examples カラム（JSONB）のみ使用

-- 普通の例文テーブル（word_id で words.id に紐づく。words.id は bigint）
create table if not exists word_sentences (
  id bigint primary key generated by default as identity,
  word_id bigint not null references words(id) on delete cascade,
  sentence_en text,
  sentence_jp text,
  sort_order int not null default 0,
  created_at timestamptz default now()
);

alter table word_sentences enable row level security;
create policy "Allow public read word_sentences"
  on word_sentences for select using (true);

comment on table word_sentences is '単語に紐づく普通の例文（語彙カードで表示）。word_id で words と紐づく。';
comment on column word_sentences.sentence_en is '例文（英語）';
comment on column word_sentences.sentence_jp is '例文の日本語訳';

-- 穴埋めクイズ用：words に examples カラムを追加（Table Editor の「examples」で編集）
-- 形式: [ {"sentenceEn": "英文（___が空欄）", "sentenceJp": "日本語"}, ... ]  正解はその行の en
alter table words
  add column if not exists examples jsonb default '[]';

comment on column words.examples is '穴埋めクイズ用。例: [{"sentenceEn":"Move the ___ to the end.","sentenceJp":"___を行末に移動する。"}]';

-- 既存の example_sentence_en/jp を word_sentences に移行したい場合は以下を実行（任意）
-- insert into word_sentences (word_id, sentence_en, sentence_jp, sort_order)
-- select id, example_sentence_en, example_sentence_jp, 0 from words
-- where example_sentence_en is not null or example_sentence_jp is not null;
